include users/manna-harbour_miryoku/rules.mk

INTROSPECTION_KEYMAP_C = matt_ftw.c
DEFERRED_EXEC_ENABLE = yes
CONVERT_TO=promicro_rp2040
MASTER=left
MIRYOKU_ALPHAS=COLEMAKDH
MIRYOKU_EXTRA=COLEMAKDH
MIRYOKU_TAP=COLEMAKDH
MIRYOKU_CLIPBOARD=WIN
